### ISSUE TITLE
Parsing interrupted when incorrect NUnit file is passed to the plugin

### ISSUE THREAD

**Issue by Greybird** [Greybird/categories-report-plugin#5]
Caused byt he following exception:
`[org.xml.sax.SAXParseException; systemId: file:###REDACTED###; lineNumber: 1; columnNumber: 1; Premature end of file.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
	at org.jenkinsci.plugins.categoriesreport.NUnitProcessor$NUnitLocalProcessor.appendFile(NUnitProcessor.java:97)
	at org.jenkinsci.plugins.categoriesreport.NUnitProcessor$NUnitLocalProcessor.invoke(NUnitProcessor.java:85)
	at org.jenkinsci.plugins.categoriesreport.NUnitProcessor$NUnitLocalProcessor.invoke(NUnitProcessor.java:59)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2749)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by Greybird** [comment]
Fixed by 87b958e45e33d79300ede2dd149e377db4f9b22e
